export const LAYOUT_CONSTANTS = {
  TILE_WIDTH: 140,
  TILE_HEIGHT: 48,
  GRID_GAP: 8,
  CONTAINER_HEADER_HEIGHT: 36,
  CONTAINER_MIN_WIDTH: 120,
  CONTAINER_MIN_HEIGHT: 80,
  CONTAINER_DEFAULT_WIDTH: 240,
  CONTAINER_DEFAULT_HEIGHT: 160,
} as const

export const STORAGE_CONSTANTS = {
  KEY_PREFIX: 'chotolate:board',
  VERSION: 1,
  AUTO_SAVE_DEBOUNCE_MS: 500,
} as const

export const UI_CONSTANTS = {
  SIDEBAR_WIDTH: 240,
  COMPLETED_BANK_HEIGHT: 140,
  MAX_UNDO_ENTRIES: 20,
  UNDO_TTL_MS: 10_000,
  BOARD_ZOOM_MIN: 0.5,
  BOARD_ZOOM_MAX: 2,
  BOARD_ZOOM_STEP: 0.1,
  BOARD_ZOOM_DEFAULT: 1,
} as const
